# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areamap',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kmlmap',
            name='area_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.AreaMap'),
        ),
        migrations.AddField(
            model_name='kmlmap',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kmlmap',
            name='dataset_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kmlmap',
            name='kml_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/datamap/'),
        ),
    ]
