# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20160926_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='areamap',
            name='area_default_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='areamap',
            name='area_external_identifier_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='areamap',
            name='area_name_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[('UNCATEGORIZED', 'Uncategorized'), ('NEIGHBORHOOD', 'Neighborhood'), ('WARD', 'Ward'), ('DISTRICT', 'District'), ('STATE', 'State'), ('COUNTRY', 'Country'), ('REGION', 'Region'), ('COUNTY', 'County')], max_length=50),
        ),
        migrations.AlterField(
            model_name='areamap',
            name='areas',
            field=models.ManyToManyField(blank=True, null=True, to='map.Area'),
        ),
    ]
